import turtle
turtle.home()
turtle.reset()

turtle.pendown()
turtle.circle(100)
turtle.penup()
turtle.left(90)
turtle.forward(100)
turtle.left(45)
turtle.forward(50)
turtle.pendown()
turtle.circle(20)
turtle.penup()
turtle.right(130)
turtle.forward(80)
turtle.left(180)
turtle.pendown()
turtle.circle(20)
turtle.penup()
turtle.left(90)
turtle.forward(80)
turtle.right(45)
turtle.left(180)
turtle.pendown()
turtle.circle(70,-80)
turtle.penup()
input ('press enter to exit')
